# Generated by Django 5.1.1 on 2025-04-30 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chat_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_data',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 12, 55, 0, 794208)),
        ),
    ]
