# Generated by Django 5.2 on 2025-05-05 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_document_file_data_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 11, 33, 43, 118015)),
        ),
    ]
