# Generated by Django 5.2 on 2025-05-05 14:00

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_chat_created_at_alter_chat_name_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.chat'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default='', upload_to=accounts.models.user_chat_directory_path),
            preserve_default=False,
        ),
    ]
