# Generated by Django 5.2 on 2025-05-31 08:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_document_extracted_text_alter_document_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=accounts.models.document_upload_path),
        ),
    ]
